// This file was generated by prisma-field-encryption.

import type { PrismaClient, Organization } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = Organization['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'Organization',
    client,
    getTotalCount: client.organization.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.organization.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        key: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.organization.update({
      where: {
        id: record.id
      },
      data: {
        key: record.key
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "key": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "users": {
 *       "modelName": "UserOrganization",
 *       "isList": true
 *     },
 *     "notifications": {
 *       "modelName": "Notifications",
 *       "isList": true
 *     },
 *     "subscription": {
 *       "modelName": "Subscription",
 *       "isList": false
 *     }
 *   }
 * }
 */
